SET hive.exec.dynamic.partition = true;
SET hive.exec.dynamic.partition.mode = nonstrict;

INSERT INTO TABLE CDW_SAPP_F_CREDIT_CARD
PARTITION (TRANSACTION_TYPE)
SELECT TRANSACTION_ID, CREDIT_CARD_NO AS CUST_CC_NO,
date(CONCAT(YEAR,'-',MONTH,'-',DAY)) AS TIMEID,
CUST_SSN, BRANCH_CODE,TRANSACTION_VALUE, TRANSACTION_TYPE
FROM CDW_SAPP_CREDITCARD;